doc: Add traffic source plugins and API locations to README
apiclarity/apiclarity pull request #84
Opened 2022-02-15 19:45 UTC by akpsgit

2022-02-15 19:49 UTC, kaechele requested changes

2022-02-15 20:18 UTC, kaechele approved these changes

2022-02-16 05:33 UTC, FrimIdan commented
@akpsgit commit prefix should be `docs:` to [be ignored by goreleaser](https://github.com/apiclarity/apiclarity/blob/master/.goreleaser.yml#L45)

2022-02-16 07:50 UTC, jadiaconu approved these changes

2022-02-16 08:11 UTC, merged